### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ghost** [sulaimanvesal/CapsNet#1]
I'm looking for the modified code of the CapsNet that you used to train on the CIFAR-10 data and it is not available here. Are you planning to add the architecture code?

**Comment by sulaimanvesal** [comment]
I have added my single script which contains the code for three datasets. The code mostly inspired by @XifengGuo implementation.

**Comment by ghost** [comment]
@sulaimanvesal Tats a great job. Thanks 👍
